# Generated by Django 5.2.11 on 2026-02-28 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('opening_time', models.TimeField(default='06:00:00')),
                ('closing_time', models.TimeField(default='23:00:00')),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('contact_number', models.CharField(blank=True, default='', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stations',
            },
        ),
        migrations.CreateModel(
            name='Charger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charger_type', models.CharField(choices=[('Type2', 'Type 2 AC'), ('CCS', 'CCS DC'), ('DC-Fast', 'DC Fast'), ('CHAdeMO', 'CHAdeMO')], max_length=20)),
                ('power_kw', models.DecimalField(decimal_places=2, max_digits=6)),
                ('connector_type', models.CharField(max_length=20)),
                ('base_price_per_kwh', models.DecimalField(decimal_places=2, max_digits=6)),
                ('status', models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('maintenance', 'Maintenance'), ('offline', 'Offline')], default='available', max_length=20)),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('last_maintenance', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chargers', to='stations.station')),
            ],
            options={
                'db_table': 'chargers',
            },
        ),
        migrations.AddIndex(
            model_name='station',
            index=models.Index(fields=['latitude', 'longitude'], name='stations_latitud_2690e9_idx'),
        ),
        migrations.AddIndex(
            model_name='station',
            index=models.Index(fields=['city'], name='stations_city_330b17_idx'),
        ),
        migrations.AddIndex(
            model_name='station',
            index=models.Index(fields=['is_active'], name='stations_is_acti_06b528_idx'),
        ),
        migrations.AddIndex(
            model_name='charger',
            index=models.Index(fields=['status'], name='chargers_status_0a110d_idx'),
        ),
        migrations.AddIndex(
            model_name='charger',
            index=models.Index(fields=['charger_type'], name='chargers_charger_dad5db_idx'),
        ),
    ]
