# Generated by Django 5.2.11 on 2026-02-28 14:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='charger',
            index=models.Index(fields=['station', 'status'], name='chargers_station_5c474a_idx'),
        ),
        migrations.AddIndex(
            model_name='station',
            index=models.Index(fields=['latitude'], name='stations_latitud_446ff5_idx'),
        ),
        migrations.AddIndex(
            model_name='station',
            index=models.Index(fields=['longitude'], name='stations_longitu_bbab95_idx'),
        ),
    ]
