# Generated by Django 5.2.11 on 2026-02-28 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('stations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('charger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='stations.charger')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='accounts.vehicle')),
            ],
            options={
                'db_table': 'bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChargingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('energy_consumed_kwh', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('base_rate_per_kwh', models.DecimalField(decimal_places=2, max_digits=6)),
                ('peak_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('pricing_tier', models.CharField(default='normal', max_length=20)),
                ('energy_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('overstay_minutes', models.PositiveIntegerField(default=0)),
                ('overstay_fine', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session', to='charging.booking')),
                ('charger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='stations.charger')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charging_sessions', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='accounts.vehicle')),
            ],
            options={
                'db_table': 'charging_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='bookings_status_51373b_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['scheduled_start', 'scheduled_end'], name='bookings_schedul_41cd7a_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', 'status'], name='bookings_user_id_1eeb34_idx'),
        ),
        migrations.AddIndex(
            model_name='chargingsession',
            index=models.Index(fields=['status'], name='charging_se_status_8728f5_idx'),
        ),
        migrations.AddIndex(
            model_name='chargingsession',
            index=models.Index(fields=['user', 'status'], name='charging_se_user_id_04e506_idx'),
        ),
        migrations.AddIndex(
            model_name='chargingsession',
            index=models.Index(fields=['start_time'], name='charging_se_start_t_dd627b_idx'),
        ),
    ]
