# Generated by Django 5.2.11 on 2026-02-28 14:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('charging', '0001_initial'),
        ('stations', '0002_add_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['charger', 'status', 'scheduled_start', 'scheduled_end'], name='bookings_charger_8ccaf3_idx'),
        ),
    ]
